{% set name = "metaprokka" %}
{% set version = "1.14.6_1" %}
{% set sha256 = "" %}

package:
  name: '{{ name }}'
  version: '{{ version }}'

source:
  url: https://github.com/tseemann/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: '{{ sha256 }}'

build:
  number: 0
  noarch: generic

requirements:
  host:
    - perl
    - perl-bioperl >=1.7.2
  run:
    - perl
    - prokka =1.14.6

test:
  commands:
    - metaprokka --listdb
    - metaprokka --version 2>&1 | grep {{ version }}
    - blastp -help
    - barrnap --help 2>&1 | grep Options
    - prodigal -h

about:
  home: https://github.com/telatin/{{ name }}
  license: GPLv3
  license_family: GPL
  summary: Rapid annotation of prokaryotic genomes
  dev_url: https://github.com/tseemann/{{ name }}

extra:
  identifiers:
    - biotools:{{ name }}
    - doi:10.1093/bioinformatics/btu153
